<a href="https://colab.research.google.com/github/MekhzZ/LearningPath/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Basics**

In [1]:
import numpy as np

In [2]:
#Defining arrays

#1D
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
#2D
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
#3d

a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [5]:
 # checking which dimension is in particular array
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [6]:
#shape of an arrays

a1.shape,a2.shape,a3.shape

((3,), (2, 3), (1, 3, 3))

a1 shape represents the singular data in one variable

a2 shape represents the num of rows and columns

a3 shape repesents the num of 2d array present in 3d array with respective rows and columns

In [7]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#reshape

a2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
# fill with zeros

np.zeros_like(a2)

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
#fill with ones
np.ones(a2.shape)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#fill with random numbers
np.random.rand(3,2)

array([[0.31416271, 0.56772108],
       [0.16869614, 0.45339095],
       [0.41030973, 0.20116999]])

In [12]:
np.random.randint(10,size=(3,2))
# 10 = max limit of random numbers

array([[8, 8],
       [2, 8],
       [8, 7]])

In [13]:
np.random.rand(3,2).dtype

dtype('float64')

In [14]:
np.random.randint(10,size=(3,2)).dtype

dtype('int64')

#**Stacking and subsetting numpy arrays**

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [16]:
print(a)
print(b)

[1 2 3]
[4 5 6]


In [18]:
#vertical stacking

vs = np.vstack([a,b])

In [19]:
vs

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
vs.shape

(2, 3)

In [21]:
vs.ndim

2

In [22]:
#horizontal stacking

hs = np.hstack([a,b])
hs

array([1, 2, 3, 4, 5, 6])

In [23]:
hs.ndim

1

In [24]:
hs.shape

(6,)

In [25]:
#subsettting

a

array([1, 2, 3])

In [26]:
a[1]

2

In [29]:
a[[0,1]]

array([1, 2])

In [30]:
#2d array

a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
a2.ndim


2

In [32]:
a2[0][1]

2

In [33]:
a2[0][2]

3

In [35]:
a2[:,1] #1 column ko sab row

array([2, 5])

In [36]:
a2[:,2]

array([3, 6])

In [37]:
a2[0,:]

array([1, 2, 3])

In [38]:
#using boolean

a2

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
a2>2

array([[False, False,  True],
       [ True,  True,  True]])

In [42]:
a2[a2>2]

array([3, 4, 5, 6])

In [43]:
a2[a2>2].shape

(4,)

In [44]:
#replacing values in aarray

a

array([1, 2, 3])

In [45]:
a[0]=100

In [46]:
a

array([100,   2,   3])

In [47]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
a2[0,1]=100

In [49]:
a2

array([[  1, 100,   3],
       [  4,   5,   6]])

In [50]:
a2[0][1]

100

In [53]:
a2[a2>2] = 80

In [54]:
a2

array([[ 1, 80, 80],
       [80, 80, 80]])